import { ArrowRight, Heart, Mail, MapPin, Play, Send, Star } from "lucide-react";
import { BrowserRouter, Link, Route, Routes } from "react-router-dom";
import Navbar from "./components/layout/Navbar";
import Hero from "./components/sections/Hero";
import sainImage from "./assets/images/sain.jpeg";
import { MediaGallery, MediaVideos } from "./components/sections/MediaSections";
import AboutStory from "./components/sections/AboutStory";

const values = [["Love for all", "Let kindness become the language that connects every heart."], ["Selfless service", "Find joy in easing another person's path, without expectation."], ["Inner peace", "Turn within with devotion, remembrance and a grateful heart."]];
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}) { return <section className="page-heading"><div className="page-shell max-w-3xl"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>; }
function Home(){return <><Hero/><section className="section bg-white"><div className="page-shell"><span className="eyebrow">The guiding light</span><h2 className="section-title max-w-2xl">A message that reaches every heart</h2><p className="mt-5 max-w-2xl leading-8 text-[#715f56]">The teachings of Sain Sadhram Sahib invite us into a life of sincere devotion, humility and human unity.</p><div className="mt-12 grid gap-5 md:grid-cols-3">{values.map(([t,d],i)=><article key={t} className="rounded-2xl border border-[#eee2d4] bg-[#fffdf9] p-7"><span className="text-[#b68625]">0{i+1}</span><h3 className="mt-4 font-serif text-2xl text-[#3d0b13]">{t}</h3><p className="mt-3 text-sm leading-7 text-[#806e64]">{d}</p></article>)}</div></div></section><section className="section bg-[#3d0b13] text-white"><div className="page-shell"><span className="eyebrow text-[#edc867]">Daily inspiration</span><blockquote className="mt-4 max-w-4xl font-serif text-3xl leading-snug sm:text-4xl">“The greatest worship is to serve humanity with a heart full of love.”</blockquote><Link to="/teachings" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#f0ca70]">Read more teachings <ArrowRight size={16}/></Link></div></section></>}
function About(){return <><Heading eyebrow="About Satguru" title="A beacon of compassion and humanity" text="A journey of spiritual dedication guided by the belief that every human being deserves love, dignity and care."/><section className="section bg-white"><div className="page-shell grid gap-12 lg:grid-cols-[.75fr_1fr]"><img src={sainImage} alt="Sain Sadhram Sahib" className="min-h-[360px] w-full rounded-3xl object-cover shadow-lg"/><div><span className="eyebrow">His vision</span><h2 className="section-title">To make service a way of life</h2><p className="body-copy mt-6">Sain Sadhram Sahib’s life and message continue to inspire people to look beyond division and recognise the shared light in all of humanity.</p><p className="body-copy mt-5">Through devotion, humility, charity and deep concern for those in need, his teachings offer a gentle, practical way to bring spirituality into everyday life.</p></div></div></section></>}
function Teachings(){const q=["See God in every living being, and serve each one with respect.","The heart that gives without expectation is always rich.","Peace begins when we let go of judgement and choose compassion.","Let your conduct be your prayer and your kindness your offering."];return <><Heading eyebrow="Teachings" title="Simple truths for a meaningful life" text="Words to carry into the small, ordinary moments where love and faith take root."/><section className="section bg-white"><div className="page-shell grid gap-5 md:grid-cols-2">{q.map((x,i)=><article className="rounded-3xl border border-[#eadfce] p-8" key={x}><Star className="text-[#bd8b28]" size={20} fill="currentColor"/><p className="mt-6 font-serif text-2xl leading-snug text-[#3d0b13]">“{x}”</p><span className="mt-7 block text-xs font-semibold uppercase tracking-[.16em] text-[#a17955]">Teaching {String(i+1).padStart(2,"0")}</span></article>)}</div></section></>}
function Gallery(){return <><Heading eyebrow="Gallery" title="Moments of devotion and togetherness" text="A glimpse into gatherings shaped by prayer, seva and the warmth of a shared spiritual path."/><section className="section bg-white"><div className="page-shell gallery-grid">{["Blessings","Prayer","Togetherness","Service","Devotion","Peace"].map((x,i)=><figure className="gallery-item" key={x}><img src={sainImage} alt={x}/><figcaption>{x}</figcaption></figure>)}</div></section></>}
function Videos(){return <><Heading eyebrow="Video library" title="Watch, reflect and reconnect" text="A place for devotional messages, satsangs and moments of spiritual reflection."/><section className="section bg-white"><div className="page-shell grid gap-6 md:grid-cols-3">{["A message of love","The beauty of seva","Finding inner peace"].map(x=><article key={x} className="overflow-hidden rounded-3xl border border-[#eadfce]"><div className="relative h-52"><img className="h-full w-full object-cover" src={sainImage} alt=""/><button aria-label={`Play ${x}`} className="absolute inset-0 m-auto h-14 w-14 rounded-full bg-white text-[#9d7017]"><Play className="mx-auto" size={20} fill="currentColor"/></button></div><div className="p-6"><span className="text-xs font-semibold uppercase tracking-wider text-[#b68625]">Satsang</span><h2 className="mt-2 font-serif text-2xl text-[#3d0b13]">{x}</h2></div></article>)}</div></section></>}
function Contact(){return <><Heading eyebrow="Connect with us" title="We would love to hear from you" text="For spiritual gatherings, seva opportunities or general enquiries, send us a message."/><section className="section bg-white"><div className="page-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl bg-[#3d0b13] p-8 text-white"><Heart className="text-[#f2ce74]" fill="currentColor"/><h2 className="mt-6 font-serif text-3xl text-white">Walk the path together</h2><p className="mt-5 flex gap-3 text-sm"><Mail size={18}/> hello@satgurusain.org</p><p className="mt-4 flex gap-3 text-sm"><MapPin size={18}/> Serving communities worldwide</p></div><form className="grid gap-5 rounded-3xl border border-[#eadfce] p-7 sm:grid-cols-2"><label>Your name<input placeholder="Your name"/></label><label>Email address<input placeholder="you@example.com"/></label><label className="sm:col-span-2">Subject<input placeholder="How can we help?"/></label><label className="sm:col-span-2">Message<textarea rows={5} placeholder="Write your message..."/></label><button type="button" className="btn-primary w-fit sm:col-span-2">Send message <Send size={16}/></button></form></div></section></>}
function Footer(){return <footer className="bg-[#2b0910] py-10 text-center text-sm text-[#ddcec7]"><p className="font-serif text-xl text-[#f0ca70]">SATGURU</p><p className="mt-2">Sain Sadhram Sahib</p><p className="mt-5 text-xs text-[#ab928a]">© {new Date().getFullYear()} · With love, faith and service</p></footer>}
export default function App(){return <BrowserRouter><Navbar/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<AboutStory/>}/><Route path="/gallery" element={<MediaGallery/>}/><Route path="/videos" element={<MediaVideos/>}/><Route path="*" element={<Home/>}/></Routes></main><Footer/></BrowserRouter>}
export { About, Teachings, Contact, Gallery, Videos };
